FROM registry.fedoraproject.org/fedora:44

RUN dnf install -y \
        cmake \
        gcc-c++ \
        gdb \
        git \
        kf6-kirigami \
        ninja-build \
        qt6-qtbase-devel \
        qt6-qtdeclarative-devel \
        qt6-qtmultimedia-devel \
    && dnf clean all

